version: '3.8'

services:
  app:
    build:
      context: .
    container_name: server-container-1
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://stas:angst0437@db:5432/mydatabase
    volumes:
      - ./app:/code/app

  db:
    image: postgres:13
    container_name: postgres-container
    environment:
      POSTGRES_USER: stas
      POSTGRES_PASSWORD: angst0437
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d/

volumes:
  postgres-data:
